[v1]
"cargo-deny 0.14.2 (path+file:///C:/buildbot/src/android/rust-toolchain/toolchain/cargo-deny)" = ["cargo-deny.exe"]
"cargo-vet 0.8.0 (path+file:///C:/buildbot/src/android/rust-toolchain/toolchain/cargo-vet)" = ["cargo-vet.exe"]
