[v1]
"cargo-deny 0.14.2 (path+file:///buildbot/src/android/rust-toolchain/toolchain/cargo-deny)" = ["cargo-deny"]
"cargo-vet 0.8.0 (path+file:///buildbot/src/android/rust-toolchain/toolchain/cargo-vet)" = ["cargo-vet"]
